services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    api_middleware.convert_json_request_middleware:
        class: 'Jalismrs\ApiMiddlewareBundle\ConvertJsonRequestMiddleware'
    
    api_middleware.is_api_controller_middleware:
        class: 'Jalismrs\ApiMiddlewareBundle\IsApiControllerMiddleware'
