services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # event-subscribers
    jalismrs_api_middleware.event_subscriber.convert_json_request_middleware:
        class: 'Jalismrs\Symfony\Bundle\JalismrsApiMiddlewareBundle\EventSubscriber\ConvertJsonRequestMiddleware'

    jalismrs_api_middleware.event_subscriber.is_api_controller_middleware:
        class: 'Jalismrs\Symfony\Bundle\JalismrsApiMiddlewareBundle\EventSubscriber\IsApiControllerMiddleware'
