services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_api_middleware.convert_json_request_middleware:
        class: 'Jalismrs\Symfony\Bundle\JalismrsApiMiddlewareBundle\ConvertJsonRequestMiddleware'

    jalismrs_api_middleware.is_api_controller_middleware:
        class: 'Jalismrs\Symfony\Bundle\JalismrsApiMiddlewareBundle\IsApiControllerMiddleware'
